/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 21.03.2026 19:33:09

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 6
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 12
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace tflite_model_trigger {

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 10704;
#else
constexpr int kTensorArenaSize = 9680;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,3960 } };
const TfArray<1, float> quant0_scale = { 1, { 0.0037683823611587286, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 99, 40, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 99, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 50, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 50, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[4] = { 1, 1, 25, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { 1, 25, 1, 32, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data7[2] = { -1, 416, };
const TfArray<1, int> tensor_dimension7 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data8[2] = { -2471, 2471, };
const TfArray<1, float> quant8_scale = { 1, { 4.3660083974828012e-06, } };
const TfArray<1, int> quant8_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[2*416] = { 
  11, 18, -20, -35, -58, 66, 55, -69, 8, -72, 6, -1, 9, 18, 49, -28, -69, -18, 71, -57, 68, -22, 75, 35, -55, 66, -28, 54, -37, -39, -32, 22, -37, 89, 69, -37, -37, -2, 24, -33, -77, -29, 18, -4, -50, -58, 54, -19, -11, 38, 76, -39, 41, -67, 70, -32, 41, 4, -34, -4, -61, 53, 3, -54, 89, 42, 52, 4, 55, -7, 56, -53, -59, 45, -73, 46, -68, -22, -13, -13, -87, -3, -24, 3, -54, 56, 42, -45, -80, 59, -14, -67, 3, 32, 16, -85, 93, -11, 26, -10, 55, 40, -71, -29, 23, 9, 19, 28, -84, 63, -48, -57, -60, -13, 47, 21, -11, -36, -70, -20, -53, 66, 18, 36, 35, -63, 29, -7, 55, 54, -9, 34, 37, 72, -17, -70, -51, -62, -86, 18, -20, 38, 33, 56, 37, 66, -28, -96, -57, -78, -19, -37, -31, 71, -25, -26, -39, 56, 16, 11, 46, -13, -30, -30, 50, 44, 14, -50, -62, 88, -48, 10, -35, -3, -71, 76, -80, -60, 77, -64, -64, -70, -7, 43, -71, 22, -3, -78, -33, 69, 54, 17, 35, 10, -15, 63, 9, 36, 36, -57, -47, 52, -76, -50, -54, -18, -45, -48, -5, -32, 3, 26, 43, 6, -6, 30, -70, -11, -9, 58, 50, 4, 66, 44, -6, 75, 104, 91, 15, -12, -44, -76, -88, 74, -24, -73, -102, -41, 13, -14, 15, 70, 62, -34, -91, 24, 13, -39, -63, 80, 75, -13, 82, 49, 24, -38, -12, -18, 49, 33, 4, 29, -39, 6, 28, -43, 23, 58, -62, -49, -45, -4, -63, -24, 59, -61, 41, -74, 13, -3, -9, 119, 56, 62, 57, -5, 23, 50, -1, 121, -6, 11, -63, -6, 64, 28, -14, -51, -53, -19, -3, -46, 40, 1, -75, -41, 37, 21, -10, 11, 60, -41, -101, 25, -5, -21, -5, 13, 0, 6, 68, -18, 35, -25, -51, -59, 14, -85, 12, 32, -54, -54, 29, 13, 9, 100, 16, 12, 5, -35, -39, -33, -59, 5, 1, 100, 61, -46, 19, -25, 61, -73, 36, 50, 19, 11, -28, 4, 62, 29, -68, 35, -72, -65, 19, 53, -64, 17, -13, -3, 30, -45, 13, -5, -59, 4, -14, -34, -5, -26, 77, -45, 5, -55, 47, 42, 37, 58, 48, -18, -74, -57, -6, -3, 48, 20, 24, -15, -61, -40, 37, -36, 51, 32, -63, -11, 13, 24, -26, 4, -36, -9, 74, 66, 56, -21, 
  -86, -127, -98, -57, -53, 42, -24, -17, 27, -38, 34, 21, -14, 32, -48, -13, 48, 29, -20, 75, 19, 22, 2, 20, 61, -2, 39, -24, -50, -39, -48, 69, -77, -22, -34, 39, 28, -66, -20, 47, 16, 52, 12, -4, 30, -34, 20, 19, -32, -39, 56, 19, 53, 66, -73, -72, 100, -102, -18, -11, 28, -18, -84, 31, -32, -13, -16, 34, -6, -84, 16, -13, 46, 75, 18, -48, 116, -34, -40, 32, -16, 56, -64, 50, -10, 49, -25, 53, 63, -31, -1, -15, 2, 47, -12, -22, -18, -105, -69, 6, 62, -4, -27, 28, 57, 37, 67, -28, -11, 11, -60, -17, 73, 31, -39, 57, -26, -11, -29, -34, 0, -5, -29, -48, 5, -34, 11, -38, 34, -94, -67, 50, 34, 32, 19, -53, 77, 27, 59, 37, 16, 65, 53, 43, 96, 43, -105, 31, 76, -4, -60, -36, 25, -34, -111, 26, -20, 61, -21, 66, -51, -87, -78, -76, 40, 63, -7, -61, -15, 37, 86, -4, 49, 28, 4, 3, -40, 18, 59, -3, 27, -37, 57, -25, 36, -63, -61, 52, -46, 13, -22, 9, -67, -25, -30, 48, 11, -1, -30, -40, -1, 11, 37, -11, 39, -47, -14, -75, 10, 41, -38, 36, 64, 50, 50, 63, -20, -67, 11, 16, 30, -20, 43, -27, -65, -32, 6, -91, -56, -41, 42, -15, 16, 6, -7, -33, 32, -25, -39, -84, 43, 13, 18, 75, 68, 73, 69, -57, -18, -13, -44, 11, -16, 16, -37, 35, -108, -108, 40, 58, -19, 22, -25, 71, 56, -41, 39, 30, 42, -29, -6, 2, 40, 54, 40, 64, 83, 49, 3, 68, 26, -36, 12, 46, -70, 42, 17, -37, -56, -38, -93, 10, -54, -5, -33, 97, -31, 59, 100, 26, 86, -16, -55, -47, 1, -5, -14, 66, -32, 53, -33, 19, -12, -76, -95, -31, -42, -53, -34, -11, -20, -76, -32, -26, 34, -63, -35, 74, 51, -28, 86, 16, 70, 52, 5, -12, -16, -8, 38, -31, -8, -20, -67, -33, 69, -20, 6, 1, 49, 3, -68, 11, -24, -35, -40, -22, -43, -14, 58, 32, 55, -16, 25, -46, 50, -12, 43, 18, -16, 30, -48, 51, 32, 80, -45, 31, 50, -20, 51, -10, -36, 52, 18, -9, -5, -40, -40, -45, 28, -22, -65, 66, -11, -40, 19, -2, 44, -61, -21, -55, -39, 4, 2, 22, 73, 0, -40, -21, 63, -28, -63, -22, -65, -12, -34, 31, 
};
const TfArray<2, int> tensor_dimension9 = { 2, { 2,416 } };
const TfArray<1, float> quant9_scale = { 1, { 0.0015610276022925973, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[32] = { -1477, 5089, -2170, -7687, -17376, -7743, -10102, 2409, 567, -8302, -1692, -4170, 1353, -16433, -6404, -4360, 2222, -7065, -4037, 2869, 588, 698, -10028, -17404, 3666, 1106, -9579, -7968, -6361, -7992, -3102, -5867, };
const TfArray<1, int> tensor_dimension10 = { 1, { 32 } };
const TfArray<32, float> quant10_scale = { 32, { 5.6661078815523069e-06, 5.8161635934084188e-06, 5.7606916925578844e-06, 4.6932195800764021e-06, 4.2213514461764134e-06, 5.65298205401632e-06, 4.182493739790516e-06, 5.3418493735080119e-06, 5.315449925547e-06, 5.4461047511722427e-06, 5.0322114475420676e-06, 4.4498215174826328e-06, 6.4310424932045862e-06, 5.1977472139697056e-06, 5.063175194663927e-06, 5.598617917712545e-06, 5.2313816922833212e-06, 5.0651110541366506e-06, 5.7677334552863613e-06, 6.3879483604978304e-06, 5.0925168579851743e-06, 5.0698326958809048e-06, 4.7664793783042114e-06, 4.5586270971398335e-06, 6.2481130953528918e-06, 5.4477227422466967e-06, 4.5373158172878902e-06, 4.928712314722361e-06, 4.8745378080639057e-06, 4.5851379582018126e-06, 5.2906761993654072e-06, 5.1746001190622337e-06, } };
const TfArray<32, int> quant10_zero = { 32, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[32*1*3*16] = { 
  /* [0][0][][] */ 71,78,-3,24,-76,-30,64,-89,59,-21,-125,-28,58,-67,35,119, 5,73,72,14,-79,-120,118,-39,12,-87,-112,-120,20,-43,98,-8, -10,-78,63,-38,-69,-20,-58,72,93,-47,-68,-127,74,48,-3,15, 
  /* [1][0][][] */ 89,-41,74,78,15,-81,83,49,-68,-76,-56,39,-72,43,28,43, 50,-49,1,-8,77,-72,35,16,86,30,7,-8,-26,58,53,-68, 17,-20,38,28,-19,-62,24,-57,-21,-19,-40,-16,-26,0,127,60, 
  /* [2][0][][] */ -73,33,101,-59,-82,-32,89,50,62,-65,-23,-92,20,30,97,72, 65,-83,74,64,-107,-65,64,-75,-54,45,20,-78,-68,24,17,-29, 87,26,-37,-12,-127,-89,-29,-14,0,-18,-98,-118,-17,56,32,105, 
  /* [3][0][][] */ -6,-102,1,-11,80,-58,12,-14,-31,-53,-44,51,-66,23,-14,-73, -12,59,93,-29,-96,-7,109,55,-28,9,-68,-17,-121,-52,-122,-73, -3,-68,-47,-127,-13,-17,27,-15,-115,-87,-4,-94,-74,107,-42,-1, 
  /* [4][0][][] */ 45,37,35,-6,63,-127,23,-104,-121,-49,-30,90,52,-14,70,59, 35,41,-79,79,36,40,-44,-8,-92,69,-82,-80,4,21,78,58, -83,36,-47,-1,45,-42,-108,-123,-98,-96,17,-73,75,-109,-93,-109, 
  /* [5][0][][] */ -18,-10,15,-2,-91,-29,72,-1,-8,-49,-68,-31,0,78,-51,34, 51,-30,-29,-47,-21,-45,107,47,44,-100,-127,32,-21,48,89,-46, 19,-3,55,32,-11,16,60,53,4,28,-13,-7,-28,33,8,34, 
  /* [6][0][][] */ 102,-113,-54,-90,69,-54,-41,72,59,58,-82,6,-110,111,-66,-118, -60,-65,-43,-44,-63,-9,-53,62,68,-71,-127,47,-115,-108,91,65, 99,-125,56,-53,7,57,-27,-41,-58,111,-44,-21,-19,-59,26,-27, 
  /* [7][0][][] */ -60,-75,-90,-60,-37,59,-2,44,-7,69,118,36,-34,39,-124,-54, -12,75,-54,-70,-65,7,39,-69,-113,23,-39,92,123,70,-126,-13, 60,127,-95,21,-16,3,1,-21,-32,58,29,46,-63,18,64,-3, 
  /* [8][0][][] */ 65,41,-99,75,-63,35,-6,69,-80,22,-9,80,21,-94,-46,-12, -95,14,15,2,104,86,-111,-2,3,-62,-68,-41,-104,-38,-46,-110, 38,94,12,16,-4,-38,-33,26,-31,62,127,-16,-61,80,-46,-100, 
  /* [9][0][][] */ -78,74,16,-56,23,-38,71,62,58,27,-66,-20,82,-30,-37,86, -85,1,37,19,-34,48,-38,-76,83,-127,33,-68,60,21,7,-42, -41,-92,50,65,51,-38,30,-20,-86,35,50,84,94,-30,-20,-10, 
  /* [10][0][][] */ -100,46,-118,-110,80,33,-1,74,-22,127,-5,81,-24,-10,-101,-3, 46,-62,-65,62,77,115,-125,113,-66,32,-29,-54,69,72,54,-62, -117,36,-27,10,-22,-18,-66,44,78,13,70,-11,-8,-78,-116,-83, 
  /* [11][0][][] */ -33,-24,-127,81,-75,-108,-37,-82,83,52,-50,-52,-57,29,-123,12, 40,72,-28,31,9,-63,52,-32,13,32,-112,-64,-63,91,-109,-3, -82,-47,1,70,6,112,17,5,20,34,41,-14,0,73,-7,-101, 
  /* [12][0][][] */ -67,1,-32,39,-26,24,-66,-31,-6,-3,82,75,97,-21,-29,-49, -96,40,22,-6,96,59,-63,-57,-46,4,127,-36,-58,16,11,-20, -30,65,-54,10,-51,65,48,-33,-53,-29,73,79,50,-66,24,-87, 
  /* [13][0][][] */ -127,9,67,63,-60,101,0,59,94,-73,47,-60,-97,-75,52,54, -32,-55,54,38,-17,-1,-32,86,-104,42,-5,-91,11,-65,6,-89, -99,85,70,3,9,61,58,-71,49,47,-31,59,26,-74,-66,80, 
  /* [14][0][][] */ -101,28,48,-7,33,42,-4,-127,-19,-44,52,27,56,8,-10,-40, -24,-14,106,-50,4,-105,-56,-78,51,19,-108,-79,59,-67,-23,20, -87,50,78,-95,-44,-73,-111,-1,-82,-60,-20,-101,99,80,7,71, 
  /* [15][0][][] */ 39,33,64,-117,-76,-79,37,-78,-58,75,38,-73,-101,-53,-62,-43, 49,26,-7,-35,-48,-18,29,53,-84,-111,-9,-92,49,-10,52,94, -16,-51,-127,-81,-53,27,-58,64,-107,-95,6,46,-101,-84,58,21, 
  /* [16][0][][] */ -12,-37,20,-90,16,86,5,-11,-105,-42,69,31,-17,-35,45,-51, -79,5,-65,-11,-19,-13,-15,63,-83,-61,73,-34,-73,-63,3,-127, 41,93,-60,-5,-60,54,-40,-71,-19,-7,-24,110,81,-38,-75,-1, 
  /* [17][0][][] */ -115,50,-86,41,9,-112,-93,-72,-39,96,-96,-72,-27,-78,-29,17, 39,-12,54,67,12,4,-24,81,56,-11,-92,-93,19,-95,-95,-7, 31,43,-68,75,-76,-111,-127,82,-54,-99,29,5,-62,-21,-80,-65, 
  /* [18][0][][] */ 69,3,85,-87,-28,-66,38,-75,51,-40,-127,-109,-13,-2,28,45, 58,-103,5,-31,5,-25,2,63,31,-38,-27,-44,41,47,-53,54, 53,-26,58,-6,-74,-114,68,56,67,-24,-12,10,-13,-13,28,38, 
  /* [19][0][][] */ 3,-70,34,-65,37,64,40,-67,-25,-50,127,-16,-13,50,-41,33, -39,65,-42,-81,19,102,27,61,-7,-39,30,-26,-50,-47,12,19, -24,5,11,61,41,33,-86,39,-23,5,-32,15,-37,-32,-47,17, 
  /* [20][0][][] */ -126,89,-91,32,33,26,-94,19,6,29,2,-30,88,23,54,-36, -77,-67,61,-109,29,-35,-4,119,-92,127,72,-28,79,45,-63,-93, 64,101,-58,-113,-11,-36,31,-26,53,39,-37,31,16,56,-30,29, 
  /* [21][0][][] */ -95,-8,-42,65,-76,83,-111,5,-46,86,-90,62,-13,-71,-127,-28, -92,-54,80,-33,9,7,80,91,-16,32,23,73,-36,-95,74,-67, -103,72,82,-84,-6,54,14,84,76,46,-13,-63,-1,-37,-111,-14, 
  /* [22][0][][] */ -107,-4,48,18,-108,-14,19,61,13,-68,-40,-112,-112,-84,-106,-79, 64,46,83,-71,90,-88,-121,-42,58,17,-72,-31,57,-85,-26,-108, 46,-34,55,-19,-124,-110,-48,64,-127,18,-75,8,-74,-17,-109,-48, 
  /* [23][0][][] */ -71,-81,-90,63,-48,29,17,-28,57,-3,43,-3,-27,119,-127,-31, -33,-2,63,-112,-36,-90,65,85,42,-24,94,100,-91,51,-9,69, -62,-54,45,26,-44,97,-23,-61,-4,-28,-32,11,29,-9,-80,-5, 
  /* [24][0][][] */ -101,17,-66,-46,24,87,-92,99,67,60,119,32,91,67,-37,-18, 32,36,-29,85,45,105,-103,16,-76,46,62,46,-35,-65,-35,-34, -89,-17,45,42,5,-13,28,-59,62,-5,-26,127,81,-85,-107,-68, 
  /* [25][0][][] */ 30,16,28,24,-104,-112,22,-18,39,-36,-111,-67,-71,32,35,-55, 72,12,-17,123,25,61,26,-87,45,-13,-127,-30,33,54,58,106, 55,-70,50,73,-52,-83,93,26,-53,-22,-113,-39,-16,-21,85,16, 
  /* [26][0][][] */ 97,38,29,-27,-46,-44,-76,-45,60,71,43,80,-96,33,63,56, 49,22,48,-8,16,64,113,-44,-25,-52,-127,-43,-120,-33,39,-126, 65,-76,79,-54,-99,-112,25,-95,-72,-56,26,97,110,-111,-57,53, 
  /* [27][0][][] */ 36,82,45,-90,-23,-23,5,-84,-84,-83,-60,-33,-97,76,-64,-30, -16,-58,73,-84,-25,67,-63,-83,34,-95,-41,-66,3,-121,-113,-28, 35,-56,-100,57,-2,67,-11,72,-47,-127,47,-109,0,-87,-75,71, 
  /* [28][0][][] */ 8,-127,7,-30,-7,-108,30,72,-43,-67,9,-97,-84,102,-49,40, 84,58,-109,87,-24,14,101,-61,-6,-52,-21,-115,-92,92,98,-100, 16,-21,60,-66,-25,-19,86,67,88,-39,-75,-15,49,-1,97,17, 
  /* [29][0][][] */ 33,47,-99,-126,7,-97,-50,50,-93,-72,19,-83,2,-70,-69,-86, -66,-68,53,-43,6,-104,6,14,92,45,32,-92,63,-54,85,-79, -89,-62,-60,-29,82,87,42,-127,43,-109,-34,44,70,-39,110,-64, 
  /* [30][0][][] */ 58,61,-50,53,17,-5,-63,-91,1,-17,-71,-124,57,23,118,3, -59,79,58,-43,77,-57,45,-99,68,-62,-127,-64,-107,92,8,77, 14,-8,-8,26,-35,13,-8,76,86,-48,0,57,66,71,-70,38, 
  /* [31][0][][] */ -52,85,15,-84,-97,-4,-6,-39,27,-117,-8,-94,-76,-16,-68,-87, -74,37,19,-81,-67,0,-74,34,-86,-117,34,38,67,44,-81,-6, 93,-112,87,54,-21,-127,117,54,-74,-29,38,16,89,-61,-53,-8, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 32,1,3,16 } };
const TfArray<32, float> quant11_scale = { 32, { 0.0021230618003755808, 0.0021792869083583355, 0.0021585018839687109, 0.0017585254972800612, 0.0015817189123481512, 0.0021181434858590364, 0.0015671590808779001, 0.002001563785597682, 0.0019916719757020473, 0.0020406276453286409, 0.0018855440430343151, 0.001667325384914875, 0.0024096788838505745, 0.001947569428011775, 0.0018971458775922656, 0.0020977735985070467, 0.0019601720850914717, 0.0018978712614625692, 0.0021611403208225965, 0.0023935316130518913, 0.0019081400241702795, 0.0018996404251083732, 0.0017859755316749215, 0.0017080942634493113, 0.0023411361034959555, 0.0020412339363247156, 0.0017001091036945581, 0.0018467634217813611, 0.001826464431360364, 0.0017180278664454818, 0.0019823894836008549, 0.0019388962537050247, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data12[16] = { -2669, -2388, -5510, -2697, 2126, 884, -395, -9643, -4577, -770, 6288, 3268, -4401, -558, -1022, 1402, };
const TfArray<1, int> tensor_dimension12 = { 1, { 16 } };
const TfArray<16, float> quant12_scale = { 16, { 1.089781380869681e-05, 1.0189739441557322e-05, 1.007811169984052e-05, 1.0206234037468676e-05, 1.066489585355157e-05, 1.032809723255923e-05, 1.0567052413534839e-05, 1.0206868864770513e-05, 9.1876727310591377e-06, 9.3172766355564818e-06, 1.2158303434262052e-05, 1.1296203410893213e-05, 9.565153050061781e-06, 1.140865970228333e-05, 1.1374041605449747e-05, 1.1850006558233872e-05, } };
const TfArray<16, int> quant12_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data13[16*1*3*8] = { 
  /* [0][0][][] */ 61,11,98,63,-53,-51,15,16, 20,-12,7,-37,-92,-24,91,-127, 60,23,38,28,-111,-89,72,6, 
  /* [1][0][][] */ -74,96,-37,77,5,-60,-54,43, -110,-36,-80,-1,91,127,33,114, 52,23,17,-110,-42,-41,-45,10, 
  /* [2][0][][] */ -3,-2,-35,-7,-17,-80,28,17, 123,-33,83,50,18,-127,16,77, -76,13,59,-86,-68,-40,84,-18, 
  /* [3][0][][] */ 71,-85,46,-50,59,-38,-86,49, 23,-127,-11,75,-4,-58,-60,6, -91,0,-47,-59,31,-66,77,43, 
  /* [4][0][][] */ -60,-63,-110,-58,-83,-32,0,78, -101,-39,-65,-59,-19,72,14,11, 51,83,75,-46,-96,127,-42,30, 
  /* [5][0][][] */ -121,80,38,78,-6,-70,-79,122, -116,58,-61,-31,93,114,-120,-15, -98,127,22,59,26,52,-96,84, 
  /* [6][0][][] */ 108,-23,52,51,-111,-48,57,-1, 65,-91,63,-97,-48,-35,47,49, -20,-127,-58,67,-29,-12,-61,-106, 
  /* [7][0][][] */ -78,80,-55,-127,-118,112,47,35, 7,59,44,72,61,75,16,46, -38,-6,-126,-42,72,60,57,29, 
  /* [8][0][][] */ 67,-127,114,59,-4,-78,122,41, -7,-124,-78,74,68,-79,-108,82, -18,-82,106,46,-15,12,-4,-59, 
  /* [9][0][][] */ 11,-70,34,85,-36,127,65,75, -64,-38,-46,-74,19,94,-78,45, -41,-69,-63,105,-21,90,-78,123, 
  /* [10][0][][] */ -82,-12,-44,38,45,17,29,17, -78,-40,-26,0,12,-35,-76,56, -64,22,-28,62,-11,97,-30,127, 
  /* [11][0][][] */ -105,63,-56,91,87,44,-59,-49, -60,-38,34,39,127,-76,-27,76, -47,14,-84,73,-60,-68,-86,-3, 
  /* [12][0][][] */ -107,57,-108,120,-48,-7,85,-38, 29,-14,-127,-68,-121,82,-126,-40, 34,61,57,30,61,-123,-90,58, 
  /* [13][0][][] */ 20,-17,-10,-55,-112,54,-48,-49, 86,19,-58,-6,-127,-100,-41,-88, -35,9,100,-14,60,-95,-45,38, 
  /* [14][0][][] */ 81,-17,68,-43,-49,10,39,-86, 12,59,98,4,-35,-35,70,-87, 110,-127,19,85,7,-127,23,-104, 
  /* [15][0][][] */ 85,46,-4,-42,5,-55,-5,42, 6,-23,70,-28,-1,-64,18,13, -43,-107,75,-58,-127,-42,40,30, 
};
const TfArray<4, int> tensor_dimension13 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant13_scale = { 16, { 0.0025457001756876707, 0.0023802958894520998, 0.0023542200215160847, 0.0023841490037739277, 0.0024912911467254162, 0.0024126160424202681, 0.0024684353265911341, 0.0023842973168939352, 0.0021462158765643835, 0.0021764910779893398, 0.002840147353708744, 0.0026387630496174097, 0.002234394196420908, 0.0026650323998183012, 0.002656945725902915, 0.0027681300416588783, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data14[8] = { -66, -1483, -2607, -18345, 871, 2426, -2034, -1652, };
const TfArray<1, int> tensor_dimension14 = { 1, { 8 } };
const TfArray<8, float> quant14_scale = { 8, { 1.2539170711534098e-05, 1.2479312317736913e-05, 1.0108978131029289e-05, 6.4915057009784505e-06, 1.4608336641686037e-05, 1.4689449926663656e-05, 1.0258348083880264e-05, 1.0663177818059921e-05, } };
const TfArray<8, int> quant14_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&quant14_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data15[8*1*3*40] = { 
  /* [0][0][][] */ 32,-5,-47,-46,-94,-34,22,-8,4,-11,-2,-40,40,-33,-36,28,-6,-22,-20,-28,5,8,11,16,13,15,0,-11,7,-26,-28,19,6,-25,9,-3,12,-9,38,127, 56,-15,-84,11,-63,-71,45,42,15,13,41,59,-29,54,20,23,40,26,13,26,-31,42,17,11,5,-20,23,19,23,2,-29,34,-15,-34,-6,4,32,5,-17,101, 68,-35,1,-62,1,-87,-39,1,18,34,-13,-15,30,-31,-24,-7,-41,-12,8,-39,26,-28,-5,14,1,-16,-46,8,-17,7,-20,-33,-10,2,-21,-22,-18,32,19,116, 
  /* [1][0][][] */ -81,-22,16,57,-13,76,-41,31,-35,19,-15,-34,29,-57,62,1,-30,-26,56,38,19,-43,12,46,20,-35,-43,-30,-33,-10,15,-42,-20,22,4,35,-37,-47,17,-101, 24,0,-15,30,12,76,42,38,-8,-32,-3,-12,25,-57,-39,43,45,-38,-16,-2,12,52,-24,-21,-39,-16,12,-26,-14,47,-9,0,-3,42,-8,-7,-9,-3,-11,-127, 22,-19,42,5,0,71,38,-7,-88,-7,-33,46,43,-44,-12,-3,-10,40,35,-9,-36,2,-49,21,15,47,-16,24,-13,-50,25,-10,13,-54,-16,53,32,20,-21,-31, 
  /* [2][0][][] */ 79,12,-93,-63,-127,-119,-3,39,7,13,37,-14,43,-42,-28,30,48,-37,59,13,58,-15,1,16,-6,-49,-41,-41,-25,-36,-41,9,-42,12,61,-24,36,-73,1,75, 74,-7,-26,-82,-39,-44,2,-6,91,-36,50,-27,-32,30,55,41,-72,-22,36,59,24,42,-42,4,-28,86,-26,-1,-30,-54,-16,41,-52,18,-26,-31,-51,35,-32,75, 67,-55,-72,-54,-34,-61,45,83,83,-35,-37,7,36,50,-3,25,-35,-57,55,-58,28,43,-45,-1,40,-48,-7,-17,1,53,63,-15,-16,-29,33,-38,32,60,-38,86, 
  /* [3][0][][] */ -99,-10,14,-84,99,-18,112,-34,44,-81,-48,-57,-30,35,10,-8,90,7,42,-2,54,55,92,111,12,73,88,-79,78,30,53,51,62,16,55,13,-43,-4,-97,32, -89,-59,1,-27,78,55,62,-74,79,61,-107,-18,-74,-58,72,-60,95,87,-9,35,78,-5,-7,96,-3,-69,63,-71,14,-31,89,94,41,-18,-67,-17,-41,-66,77,-45, 45,-12,109,-95,83,87,34,-6,-103,13,68,-66,-104,2,-67,7,59,15,-55,108,-69,8,-67,-13,-24,-26,127,-1,81,-66,106,-4,15,-41,-53,-15,4,-71,-80,-62, 
  /* [4][0][][] */ 18,8,6,59,5,37,3,29,-33,-11,-33,24,8,20,-12,29,-30,-29,-36,-44,-15,-33,-29,-17,-28,-34,-1,4,36,-22,-30,20,-36,-20,20,-36,-20,27,-28,-47, -8,23,64,11,10,35,39,-35,-10,-14,-6,8,-18,19,-25,-23,-27,-11,19,-22,-15,16,28,36,-22,38,7,-30,0,31,-56,43,-31,-38,31,9,-37,14,-50,-68, 11,-27,-7,33,22,20,36,8,-33,-22,-27,30,49,26,-30,-3,-32,-34,-10,6,-8,-1,-20,-28,5,-34,-11,-24,-17,34,23,-32,40,13,-33,27,53,34,-3,-127, 
  /* [5][0][][] */ -62,47,29,49,52,35,-20,0,-26,11,-13,40,-5,19,-4,4,-34,5,-6,20,-15,-24,54,-23,3,-31,1,3,-22,21,-49,43,1,-24,15,2,-14,-22,40,-95, -64,-11,61,66,55,15,-38,-43,-51,-29,-28,-47,0,12,-13,-4,9,-2,38,30,34,-23,4,24,-14,21,-29,23,5,11,-2,-1,-18,29,-28,-18,15,30,-27,-127, 5,-7,76,19,52,45,-12,-37,-10,48,40,9,-13,16,-5,25,33,-24,1,-40,23,39,-29,20,-7,-26,40,9,4,-28,2,23,-27,-45,-33,-19,-13,-28,4,-20, 
  /* [6][0][][] */ 64,41,-52,-15,-75,-85,-47,-31,-34,-73,-35,11,-40,-10,6,-14,-37,36,25,14,-5,36,7,-13,-45,4,73,33,31,-4,11,-56,16,-22,-38,51,-53,-3,-17,67, 7,-82,4,-48,-76,22,27,44,61,10,-29,59,-47,63,24,-18,-35,-23,31,45,-9,-51,-22,-8,-60,43,-38,69,-13,-17,53,47,-52,39,-35,41,57,46,-32,73, 35,-61,-80,-53,-127,-95,-20,-14,91,56,-42,-13,-11,-29,-26,-30,55,-43,14,23,-21,-71,47,14,21,16,-64,8,-18,43,-12,-25,-16,59,8,59,-34,-59,-55,115, 
  /* [7][0][][] */ -12,20,86,61,85,50,-34,13,-56,-40,43,-56,13,-56,-12,21,-16,73,-31,-8,-17,4,-56,-22,42,3,1,39,43,44,-32,-46,46,30,-8,-42,31,-10,27,-127, -61,42,19,15,20,23,19,31,-17,9,30,-45,5,-13,-38,-26,-37,-22,10,-56,-16,-6,35,23,13,-7,-32,-2,34,-50,-54,-5,35,26,29,-3,8,40,-16,-105, -51,32,14,35,31,32,-9,-3,-52,21,-22,-7,-74,1,26,10,22,41,29,-2,-16,21,40,40,-28,46,21,27,-33,30,40,52,-35,-7,-46,19,-47,-46,7,-84, 
};
const TfArray<4, int> tensor_dimension15 = { 4, { 8,1,3,40 } };
const TfArray<8, float> quant15_scale = { 8, { 0.0033274677116423845, 0.0033115833066403866, 0.0026825775858014822, 0.0017226239433512092, 0.0038765536155551672, 0.0038980783428996801, 0.0027222153730690479, 0.0028296431992202997, } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&g0::quant14_zero, 0 };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,99,40 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,99,8 } };
const TfArray<1, float> quant17_scale = { 1, { 0.0042808707803487778, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,99,1,8 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension20 = { 4, { 1,1,50,8 } };
const TfArray<4, int> tensor_dimension21 = { 4, { 1,1,50,16 } };
const TfArray<1, float> quant21_scale = { 1, { 0.0026688380166888237, } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension22 = { 4, { 1,50,1,16 } };
const TfArray<4, int> tensor_dimension23 = { 4, { 1,25,1,16 } };
const TfArray<4, int> tensor_dimension24 = { 4, { 1,1,25,16 } };
const TfArray<4, int> tensor_dimension25 = { 4, { 1,1,25,32 } };
const TfArray<1, float> quant25_scale = { 1, { 0.0027968809008598328, } };
const TfLiteAffineQuantization quant25 = { (TfLiteFloatArray*)&quant25_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<4, int> tensor_dimension26 = { 4, { 1,25,1,32 } };
const TfArray<4, int> tensor_dimension27 = { 4, { 1,13,1,32 } };
const TfArray<2, int> tensor_dimension28 = { 2, { 1,416 } };
const TfArray<2, int> tensor_dimension29 = { 2, { 1,2 } };
const TfArray<1, float> quant29_scale = { 1, { 0.014215521514415741, } };
const TfArray<1, int> quant29_zero = { 1, { -1 } };
const TfLiteAffineQuantization quant29 = { (TfLiteFloatArray*)&quant29_scale, (TfLiteIntArray*)&quant29_zero, 0 };
const TfArray<1, float> quant30_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant30 = { (TfLiteFloatArray*)&quant30_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 16 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 16,15,14 } };
const TfArray<1, int> outputs1 = { 1, { 17 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 17,2 } };
const TfArray<1, int> outputs2 = { 1, { 18 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 18 } };
const TfArray<1, int> outputs3 = { 1, { 19 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 19,3 } };
const TfArray<1, int> outputs4 = { 1, { 20 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 20,13,12 } };
const TfArray<1, int> outputs5 = { 1, { 21 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 21,4 } };
const TfArray<1, int> outputs6 = { 1, { 22 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 22 } };
const TfArray<1, int> outputs7 = { 1, { 23 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 23,5 } };
const TfArray<1, int> outputs8 = { 1, { 24 } };
const TfLiteConvParams opdata9 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs9 = { 3, { 24,11,10 } };
const TfArray<1, int> outputs9 = { 1, { 25 } };
const TfLiteReshapeParams opdata10 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs10 = { 2, { 25,6 } };
const TfArray<1, int> outputs10 = { 1, { 26 } };
const TfLitePoolParams opdata11 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs11 = { 1, { 26 } };
const TfArray<1, int> outputs11 = { 1, { 27 } };
const TfLiteReshapeParams opdata12 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs12 = { 2, { 27,7 } };
const TfArray<1, int> outputs12 = { 1, { 28 } };
const TfLiteFullyConnectedParams opdata13 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs13 = { 3, { 28,9,8 } };
const TfArray<1, int> outputs13 = { 1, { 29 } };
const TfLiteSoftmaxParams opdata14 = { 1 };
const TfArray<1, int> inputs14 = { 1, { 29 } };
const TfArray<1, int> outputs14 = { 1, { 30 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension0, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension7, 8, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 832, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 1536, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data12, (TfLiteIntArray*)&g0::tensor_dimension12, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data13, (TfLiteIntArray*)&g0::tensor_dimension13, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data14, (TfLiteIntArray*)&g0::tensor_dimension14, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data15, (TfLiteIntArray*)&g0::tensor_dimension15, 960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 3960, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3968), (TfLiteIntArray*)&g0::tensor_dimension17, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 792, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension19, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension21, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension23, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension24, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension25, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension26, 800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 800), (TfLiteIntArray*)&g0::tensor_dimension27, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension28, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 416), (TfLiteIntArray*)&g0::tensor_dimension29, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant29))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension29, 2, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant30))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[15] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs13, (TfLiteIntArray*)&g0::outputs13, (TfLiteIntArray*)&g0::inputs13, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata13)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs14, (TfLiteIntArray*)&g0::outputs14, (TfLiteIntArray*)&g0::inputs14, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata14)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[15] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs13, (TfLiteIntArray*)&g0::outputs13, (TfLiteIntArray*)&g0::inputs13, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata13)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs14, (TfLiteIntArray*)&g0::outputs14, (TfLiteIntArray*)&g0::inputs14, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata14)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 31, };
const size_t tflNodes_subgraph_index[] = {0, 15, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  30, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

} // end namespace tflite_model_trigger
using namespace tflite_model_trigger;

TfLiteStatus tflite_learn_935943_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  static EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 31;
  for (size_t i = 0; i < 31; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_935943_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_935943_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_935943_4_invoke() {
  for (size_t i = 0; i < 15; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_935943_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
