#line 1 "C:\\Arduino\\crySense_ai\\crySence_hardened\\crySence\\libs\\CrySense_AI_inferencing\\src\\tflite-model\\tflite_learn_922684_3_compiled.cpp"
/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 21.03.2026 18:13:06

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 6
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 12
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace tflite_model_ai {

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 3760;
#else
constexpr int kTensorArenaSize = 2736;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_MAX_POOL_2D, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,650 } };
const TfArray<1, float> quant0_scale = { 1, { 0.044064607471227646, } };
const TfArray<1, int> quant0_zero = { 1, { 28 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 1, 50, 13, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data2[4] = { 1, 50, 1, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[4] = { 1, 1, 25, 8, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data4[4] = { 1, 25, 1, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[4] = { 1, 1, 13, 16, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data6[4] = { 1, 13, 1, 32, };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data7[2] = { -1, 224, };
const TfArray<1, int> tensor_dimension7 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data8[3] = { 45, 1711, -1972, };
const TfArray<1, int> tensor_dimension8 = { 1, { 3 } };
const TfArray<1, float> quant8_scale = { 1, { 4.85408709209878e-05, } };
const TfArray<1, int> quant8_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data9[3*224] = { 
  25, -85, -2, -52, 67, -38, -87, -58, -62, 41, -24, 16, 29, 46, 13, 30, -42, -57, 66, 11, -33, 42, -5, 18, -25, -76, -28, -17, 52, 59, 1, 33, 15, -37, -20, 32, 26, -54, -25, -51, -102, -14, -58, 44, 34, 33, -55, 27, -65, -44, 18, 35, -68, -11, -48, -16, -28, 18, -33, -2, -36, 18, 18, -17, 61, -57, -29, 79, -10, -8, -5, 18, -89, 8, -56, 100, 73, 16, -19, -28, -5, -68, 39, 31, -11, 0, -85, 18, 48, 23, -50, 44, -39, 85, 68, 47, 83, 24, -26, 70, 9, -13, 17, -11, -77, 78, 4, 33, 4, -3, 81, -31, -51, -17, 5, 77, -64, 27, -90, 106, -11, -25, 59, -10, -8, 39, 71, -26, 26, -30, 21, -1, 44, -66, -9, 2, -53, -7, -82, 27, 27, 19, 75, 51, -68, -92, 48, 65, -11, -28, -9, 56, -26, -31, -19, 2, 25, -40, -32, -55, 65, -46, 11, 84, 41, -82, -5, -64, -18, 5, -65, -31, 26, 65, 26, -52, 41, -80, 52, 49, -22, 37, -54, 70, 12, -35, -14, -10, 16, 34, 20, 32, -67, -5, -7, -63, 74, -6, -105, 100, 53, 20, 3, 10, 26, 29, 53, -35, -70, -62, -3, 36, -69, -37, -76, -1, -14, -38, -28, 31, -16, -20, -73, 20, 
  -121, -46, -23, 115, -26, 75, 41, 25, 14, 54, 37, 10, 33, 110, -11, 9, 36, 1, -51, -60, 10, -12, 53, -16, 76, 65, 62, -10, -53, -79, -46, -63, -73, 38, 38, -58, -42, 52, -29, 27, 42, -5, 77, -23, 6, 70, -30, 8, -22, -51, -72, -37, 46, -22, 40, 8, 13, 3, 34, 14, -14, 5, -20, -71, -33, -59, 48, -32, -29, 30, 44, -2, -29, -61, 21, -64, -77, 21, -1, 30, -47, -10, -60, -82, 71, -29, -1, -42, 35, -75, -70, -56, -38, -5, -15, 20, 12, -84, 4, -57, -77, -31, -23, -54, -23, -6, 89, -64, -102, 13, 58, 0, -66, 12, -6, -33, 50, -48, 52, -66, -5, -56, -86, -5, -57, -10, -6, -6, -57, -55, 75, 12, -27, -25, 28, -82, 15, -48, -3, -69, -68, 41, 37, 65, -76, -29, 3, -10, 87, -37, 33, 5, -6, -62, -79, 55, -36, -30, -35, -14, -8, 27, 63, -22, 18, -9, 17, -76, -11, 9, 51, -73, -3, -1, 22, 61, -30, 13, 50, -100, -16, -53, 45, -76, 64, 11, 31, 31, 28, 83, 12, 50, -14, -51, 28, 38, -105, 61, 109, -62, -26, -5, -55, -27, -33, 55, 12, -69, -96, 28, -84, -40, 53, 122, -36, 1, 18, -30, 27, 29, -3, 118, 95, 82, 
  0, -29, -112, -30, -71, -28, -9, 38, 62, -78, -72, -15, -59, -46, 47, 16, 44, 77, -41, -44, -3, -95, 30, -4, -75, -43, -80, 40, 39, -30, 1, 51, 65, 60, -7, 73, -10, 57, -77, 21, 79, -68, 3, 4, -27, -25, 71, -86, 109, 64, 43, 6, -12, -43, 3, 25, 13, 28, -32, 28, -14, -36, 40, 22, -13, 14, 12, 29, -39, 33, 48, -1, 96, -36, -79, 25, 29, -37, -74, -72, 17, 91, 19, -15, -29, 56, 17, 48, 30, 75, 5, 18, 61, -59, 63, 43, 64, -25, -84, -22, -43, 19, -20, 5, 87, -26, -7, -95, -41, -2, -51, -70, 95, 75, 8, -35, 0, -56, 54, -55, -55, 67, 19, -32, -44, -50, 50, 26, -12, 49, -5, 29, -62, 21, -23, 36, 9, -36, -18, 50, 48, 30, -88, 8, 25, 94, 39, -46, 56, -26, 65, -35, -16, 65, -37, 4, -47, -44, 30, -46, 48, 83, -97, 44, -19, -36, 95, 94, 127, -27, -26, -67, 56, -21, -9, 5, 11, 84, -32, -48, -29, 15, 65, 48, -29, 69, 70, 22, 62, -98, -6, -43, 94, -18, -65, -43, 90, -38, -3, -6, -6, -41, -27, -51, 35, -60, 27, 56, 43, -75, 5, -38, -47, -56, 41, -56, -59, -14, 18, -28, 0, -18, -1, -4, 
};
const TfArray<2, int> tensor_dimension9 = { 2, { 3,224 } };
const TfArray<1, float> quant9_scale = { 1, { 0.0025979976635426283, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant8_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data10[32] = { -1110, -1646, 2124, -598, -803, -972, -630, -1105, -399, 434, 499, -582, -871, 756, -621, 209, -1205, -166, -493, 124, 408, 452, 781, -1105, 1162, -1141, -1753, -963, -1409, 2714, 481, 899, };
const TfArray<1, int> tensor_dimension10 = { 1, { 32 } };
const TfArray<32, float> quant10_scale = { 32, { 5.2861811127513647e-05, 4.6863002353347838e-05, 6.5276028180960566e-05, 5.8763263950822875e-05, 6.0322159697534516e-05, 4.317031562095508e-05, 4.8537749535171315e-05, 5.4304906370816752e-05, 7.3226729000452906e-05, 5.8612229622667655e-05, 5.9079920902149752e-05, 5.6774319091346115e-05, 5.6319615396205336e-05, 6.9319939939305186e-05, 6.0194855905137956e-05, 5.7063225540332496e-05, 5.1788392738671973e-05, 5.9438021708047017e-05, 4.9925969506148249e-05, 7.4086347012780607e-05, 5.3112078603589907e-05, 6.5215012000408024e-05, 4.8060108383651823e-05, 5.1881976105505601e-05, 3.9360806113108993e-05, 7.1901464252732694e-05, 5.4949508921708912e-05, 4.52179774583783e-05, 4.8880479880608618e-05, 6.2661900301463902e-05, 4.7938112402334809e-05, 5.3149342420510948e-05, } };
const TfArray<32, int> quant10_zero = { 32, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data11[32*1*3*16] = { 
  /* [0][0][][] */ 57,56,-14,-11,58,-14,55,-79,21,-66,-96,44,93,3,50,86, 29,25,72,27,-11,-93,120,-40,21,-108,-84,-87,50,25,127,27, -42,-79,75,22,-100,7,9,40,101,-66,-49,-76,26,46,-20,85, 
  /* [1][0][][] */ 97,-38,75,82,-27,-32,-3,55,-75,-57,51,127,-66,24,-35,4, 59,-47,-4,13,45,-22,-53,-2,91,14,20,21,-30,80,-18,-49, 37,-24,44,63,-54,-71,-56,-97,-17,-21,-126,44,-37,22,101,43, 
  /* [2][0][][] */ -74,39,31,-64,35,3,51,89,15,37,49,-110,38,5,54,37, -33,-13,51,5,-31,-43,37,-26,-48,127,80,-75,-34,-23,-8,-37, 6,23,-52,-30,-34,-72,-33,7,-5,55,-37,-88,-23,32,-17,46, 
  /* [3][0][][] */ -1,-56,-16,-22,11,-35,-10,-30,-1,-76,-65,24,-47,15,-12,-109, 34,40,120,54,-127,50,76,53,30,17,17,102,-89,6,-42,-60, 6,2,-2,-9,-63,22,19,17,-36,-25,53,-15,-61,48,-33,39, 
  /* [4][0][][] */ 12,26,64,22,69,-38,100,-52,-75,-41,61,62,43,8,72,75, 33,14,-44,95,37,67,-2,-43,-15,24,-22,-83,-12,39,41,127, -70,-5,-27,-16,75,-38,58,-75,-21,-51,27,-66,34,-91,-14,-31, 
  /* [5][0][][] */ 0,-5,-16,-31,-118,24,-20,11,-15,-31,-20,42,10,71,-84,-45, 49,24,-12,-31,-69,9,39,99,87,-56,-77,127,-30,41,51,-121, 67,36,46,-14,26,-3,27,92,-4,98,-90,11,-13,-62,-12,-35, 
  /* [6][0][][] */ 60,-19,-41,-72,62,-2,-21,47,103,51,-86,3,-63,82,-55,-45, -71,-44,9,-20,-6,-55,-3,78,66,-26,-127,115,-88,-127,32,-8, 99,-96,41,-75,108,30,5,-56,-57,55,0,4,33,37,50,-56, 
  /* [7][0][][] */ 62,-86,-11,-8,-120,73,26,9,44,35,123,93,-8,34,-53,-17, 77,82,-27,-31,-47,62,-11,-125,-86,-43,-20,54,89,39,-57,37, 125,49,-42,-11,-39,-9,-41,-55,-56,-39,-67,-17,-24,86,127,46, 
  /* [8][0][][] */ 127,49,-31,67,-66,-20,-13,55,-34,-15,-21,63,11,-38,-5,3, -43,47,30,38,32,-6,-69,13,27,-48,-62,-39,-48,-15,-10,-66, 102,56,4,13,-32,-55,-23,27,-14,0,-23,-40,-61,18,11,-42, 
  /* [9][0][][] */ -88,17,15,-57,-6,22,113,17,69,60,-1,-9,64,0,-27,66, -77,-10,59,6,-31,116,60,-59,87,-37,107,-20,53,15,11,2, -44,-78,60,9,-5,-16,127,-25,-60,67,75,67,41,-44,-18,36, 
  /* [10][0][][] */ -54,14,-88,-109,75,11,-52,66,-25,127,0,22,34,0,-49,-44, 45,-39,-62,25,14,71,-123,71,-24,58,-33,-85,72,84,30,-27, -76,24,11,-22,18,-22,-30,39,58,55,29,-25,15,-106,-80,-57, 
  /* [11][0][][] */ -24,-71,-50,55,-109,-72,50,-89,76,-39,-19,4,-55,59,-44,25, 17,9,-1,48,-56,-21,72,-59,47,-13,-18,14,-48,78,-35,40, -57,-26,70,116,-76,127,38,-5,29,22,89,17,-16,90,-23,33, 
  /* [12][0][][] */ -23,-15,13,79,-62,4,-18,-51,55,-49,25,114,62,-24,64,-29, -65,-14,66,13,40,57,12,-79,2,-48,116,-23,-74,26,96,56, -9,31,-20,63,-91,59,127,-68,6,-56,86,81,18,-97,75,-5, 
  /* [13][0][][] */ -54,-32,46,-16,-1,65,83,31,42,-4,54,-42,-56,-66,73,19, -23,-28,64,-7,11,32,17,52,-68,127,55,-9,36,-56,26,-39, -60,34,24,-31,-19,87,27,-37,16,83,-2,20,42,-51,-26,34, 
  /* [14][0][][] */ -53,9,38,-1,77,72,25,-50,-46,-7,127,-14,71,42,-39,16, -56,4,81,-2,40,-56,-12,-46,31,9,-17,-106,84,15,-54,83, -55,24,85,-33,26,-79,-47,-10,-20,-46,-29,-101,58,54,9,121, 
  /* [15][0][][] */ 13,76,60,-122,31,-33,11,-49,-67,127,61,-33,7,-27,-39,-39, 24,-25,-37,-79,48,-10,64,43,-51,-23,-23,-127,104,45,68,107, -41,-38,-83,-90,42,-66,19,88,-106,-8,-57,56,-56,-99,61,-19, 
  /* [16][0][][] */ 106,-29,100,-127,44,70,-45,-42,-117,-75,1,82,5,37,110,-34, 47,6,-27,-53,-86,-17,-32,40,-90,-77,22,-26,-60,34,97,4, 66,54,-12,4,-86,19,-55,-46,8,-15,-50,64,25,-33,-32,12, 
  /* [17][0][][] */ -43,76,-41,72,-26,-90,-10,-36,-11,-4,-81,-45,-27,-50,0,67, 16,36,60,127,-49,-73,-11,85,69,-52,-97,-77,-33,-99,-68,-6, -4,79,-45,113,-75,-121,-87,95,-23,-55,-69,-11,-58,-60,-67,-71, 
  /* [18][0][][] */ 11,-30,82,-57,49,-84,120,-73,43,-85,-97,-106,-11,43,77,45, 12,-117,-4,-20,2,4,45,42,36,-27,-21,-58,11,81,-34,95, -27,-35,90,12,-51,-88,127,59,123,-25,15,66,-28,-45,4,59, 
  /* [19][0][][] */ -33,-61,38,-5,5,20,127,-61,9,-60,67,-55,-13,46,-6,85, -64,25,6,-11,19,59,108,-12,22,-40,37,-6,-34,-18,22,57, -23,-10,30,69,10,26,-7,-12,-4,-16,1,-30,-37,-20,-17,85, 
  /* [20][0][][] */ -84,87,-82,47,25,-11,-98,21,10,33,-35,-63,93,50,64,-53, -62,-29,66,-100,7,-58,-45,124,-54,127,50,-17,88,9,-39,-110, 64,93,-34,-55,-20,-23,-66,-4,38,37,-5,-2,29,64,-51,3, 
  /* [21][0][][] */ -67,-18,-1,58,-55,51,-26,-26,-7,26,-87,-27,8,-14,-49,63, -92,-32,114,-20,-3,-4,127,64,30,25,2,85,-45,-50,66,-13, -63,13,49,-27,-62,62,18,20,55,14,-44,-42,-32,-29,-71,43, 
  /* [22][0][][] */ -67,59,45,48,-76,-14,-26,127,18,-72,-56,-75,-84,-77,-47,-110, 126,81,55,-6,87,-53,-82,-21,84,34,-34,16,65,-18,24,-119, 69,25,30,-2,-77,-111,-34,112,-55,53,-115,21,-37,-30,-60,-51, 
  /* [23][0][][] */ -28,-24,-18,84,-49,58,60,-39,46,-11,110,-19,-10,103,-120,62, -47,51,100,-43,-16,-44,49,57,29,-40,79,21,-59,47,-31,127, -10,-52,36,37,-54,52,-22,-50,10,-64,-62,-42,-37,-6,-59,110, 
  /* [24][0][][] */ -111,-2,-106,-80,58,68,-122,93,91,51,90,-79,82,93,14,22, 20,16,12,56,36,70,-62,24,-112,106,79,78,-80,-87,-6,-15, -117,-16,110,55,-82,-111,84,-61,123,43,-76,103,92,-127,-85,-25, 
  /* [25][0][][] */ 29,15,14,25,-127,-35,-48,12,35,-20,-55,-21,-90,-34,7,-51, 76,23,-14,66,-33,72,-17,-22,46,12,-40,83,-10,-37,40,-6, 45,-9,5,47,-35,-38,1,31,-31,-8,-58,18,3,-19,44,-41, 
  /* [26][0][][] */ 92,43,39,35,-54,13,-68,-28,127,79,38,92,-70,-6,40,35, 25,34,69,-13,-18,52,92,-7,6,-7,-77,35,-68,11,22,-108, 57,-61,63,-57,-73,-52,44,-86,-7,-26,6,91,49,-104,-40,47, 
  /* [27][0][][] */ 40,70,46,-68,-29,-62,15,-95,-67,-80,-86,-73,-93,88,-45,-16, -26,-52,69,-73,-36,40,-61,-79,34,-93,-54,-114,-10,-115,-96,-13, 17,-64,-94,73,3,51,-12,66,-45,-111,45,-127,-5,-70,-54,57, 
  /* [28][0][][] */ -11,-31,32,-18,-61,-46,-3,88,-9,-33,-2,-95,-74,56,-70,92, 16,65,-38,96,50,6,112,-47,24,-37,-65,-119,-47,98,9,-25, 62,-27,82,-43,23,-7,94,19,69,-59,-62,-48,11,2,127,65, 
  /* [29][0][][] */ -35,46,-118,-94,113,-103,80,20,-78,-30,-15,-116,44,-13,49,-88, -80,-55,16,-22,18,-127,45,30,34,20,-24,-67,32,-4,82,-46, -80,-56,-44,-4,11,43,70,-32,25,-55,-38,47,56,-27,36,-59, 
  /* [30][0][][] */ 11,86,-45,75,42,-22,-33,-28,51,-12,-103,-95,60,54,94,-22, -109,60,112,-63,2,-111,64,-20,84,-74,-127,61,-117,73,41,17, -58,-30,-34,75,-107,-7,5,37,113,-68,-29,96,45,48,-82,4, 
  /* [31][0][][] */ -50,87,10,-65,-11,-27,18,-39,14,-123,-12,-68,-83,-22,-24,-92, -56,13,-4,-48,-3,-27,-4,50,-57,-104,-13,-17,64,97,-26,12, 43,-91,127,72,-41,-89,115,68,-11,-32,77,71,60,-39,-7,11, 
};
const TfArray<4, int> tensor_dimension11 = { 4, { 32,1,3,16 } };
const TfArray<32, float> quant11_scale = { 32, { 0.0023028380237519741, 0.0020415098406374454, 0.0028436430729925632, 0.0025599251966923475, 0.0026278358418494463, 0.0018806440057232976, 0.0021144673228263855, 0.0023657041601836681, 0.0031900021713227034, 0.0025533456355333328, 0.0025737197138369083, 0.0024732800666242838, 0.0024534715339541435, 0.003019809490069747, 0.0026222900487482548, 0.0024858657270669937, 0.0022560763172805309, 0.0025893198326230049, 0.0021749429870396852, 0.0032274501863867044, 0.0023137405514717102, 0.002840984845533967, 0.0020936597138643265, 0.0022601531818509102, 0.0017146888421848416, 0.0031322692520916462, 0.0023937851656228304, 0.0019698468968272209, 0.0021293978206813335, 0.0027297628112137318, 0.0020883451215922832, 0.002315363846719265, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant10_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data12[16] = { -2691, -2200, -1191, -1771, 1834, -1162, 503, -1691, -1319, -279, 293, -786, 827, 58, -1472, -29, };
const TfArray<1, int> tensor_dimension12 = { 1, { 16 } };
const TfArray<16, float> quant12_scale = { 16, { 8.0040677858050913e-05, 6.0273425333434716e-05, 7.208510214695707e-05, 6.2069615523796529e-05, 7.6456388342194259e-05, 7.8872981248423457e-05, 8.0857105785980821e-05, 7.3230032285209745e-05, 7.2030081355478615e-05, 9.4251539849210531e-05, 9.2553687863983214e-05, 8.0756668467074633e-05, 7.2068600275088102e-05, 6.7261164076626301e-05, 6.5633939811959863e-05, 7.3630624683573842e-05, } };
const TfArray<16, int> quant12_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data13[16*1*3*8] = { 
  /* [0][0][][] */ 1,84,71,99,-40,-49,-49,9, -7,61,7,4,-118,-48,-20,-50, -5,98,42,59,-127,-50,-15,-30, 
  /* [1][0][][] */ -52,87,-22,110,22,-92,24,21, -66,-36,-103,-24,77,90,127,39, 75,52,24,-124,-61,-50,50,-30, 
  /* [2][0][][] */ -48,-46,-46,-26,-11,-40,-35,36, 84,7,95,11,85,-64,-51,127, -87,52,26,-66,-43,-33,15,-29, 
  /* [3][0][][] */ 75,-58,17,-65,127,-79,-71,53, 21,-119,-65,61,10,-73,-13,42, -43,-55,-54,-49,110,-57,77,61, 
  /* [4][0][][] */ 0,-83,-38,-46,-104,-53,12,26, -15,-29,-59,-52,-99,92,43,-16, 127,39,95,-57,-94,84,-7,12, 
  /* [5][0][][] */ -116,61,15,55,43,-70,-101,105, -127,43,-93,0,25,33,-126,-13, -126,51,-19,30,-1,2,-95,105, 
  /* [6][0][][] */ 127,-87,-23,-7,-51,-32,-5,19, 89,-77,58,-83,-19,-23,-21,98, 16,-93,-49,11,-41,-25,-82,-83, 
  /* [7][0][][] */ -50,-3,-36,-123,-87,127,116,3, -13,0,49,85,60,98,56,24, -44,-38,-65,-5,41,66,105,0, 
  /* [8][0][][] */ 63,-102,58,41,30,-68,2,75, -33,-71,-36,35,97,-54,-127,96, -46,-71,93,51,60,-14,-68,-54, 
  /* [9][0][][] */ -11,-35,16,76,-41,127,4,25, -34,-37,-35,-11,-29,93,-55,-6, -22,-38,-6,66,-16,114,-49,26, 
  /* [10][0][][] */ -35,-3,-14,-3,31,-13,-37,6, -119,19,-19,-29,-4,-6,-94,53, -127,21,-85,14,-63,47,-49,105, 
  /* [11][0][][] */ -57,-12,-71,127,30,-23,-27,-62, -9,1,89,40,106,-105,-49,41, 7,66,-75,101,-93,-76,-82,-29, 
  /* [12][0][][] */ -57,10,-83,36,-81,41,42,-44, 82,-37,-79,-41,-78,127,-66,-60, 58,9,44,-3,53,-76,-54,60, 
  /* [13][0][][] */ 21,20,-1,-58,-41,25,-75,-51, 43,57,-14,18,-57,-119,-57,-26, -78,7,118,-7,104,-127,-71,103, 
  /* [14][0][][] */ 92,31,98,-66,-55,22,5,-65, 28,108,112,22,-42,-42,6,-88, 127,-118,6,60,-14,-76,-35,-111, 
  /* [15][0][][] */ 127,44,6,-92,11,-62,-83,112, 31,-25,3,-55,-38,-47,-39,42, -7,-95,36,-56,-99,-53,-16,63, 
};
const TfArray<4, int> tensor_dimension13 = { 4, { 16,1,3,8 } };
const TfArray<16, float> quant13_scale = { 16, { 0.0030935406684875488, 0.0023295441642403603, 0.0027860610280185938, 0.00239896634593606, 0.0029550094623118639, 0.0030484097078442574, 0.0031250952742993832, 0.0028303121216595173, 0.0027839343529194593, 0.0036427848972380161, 0.0035771636757999659, 0.0031212135218083858, 0.0027854230720549822, 0.0025996176991611719, 0.002536725951358676, 0.0028457946609705687, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant12_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data14[8] = { 28, -1809, -1386, -2348, -283, -1329, -1035, -1891, };
const TfArray<1, int> tensor_dimension14 = { 1, { 8 } };
const TfArray<8, float> quant14_scale = { 8, { 0.00014865507546346635, 0.00017026529530994594, 0.00015828138566575944, 0.00014758543693460524, 0.00016449310351163149, 0.00022271921625360847, 0.00017828975978773087, 0.00014671971439383924, } };
const TfArray<8, int> quant14_zero = { 8, { 0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&quant14_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data15[8*1*3*13] = { 
  /* [0][0][][] */ 79,19,-4,106,-29,68,35,18,-39,-42,96,-127,119, -64,-74,-46,81,-7,60,-77,62,19,-14,92,-28,59, 39,-74,-58,32,-92,73,4,-13,38,-33,75,-78,73, 
  /* [1][0][][] */ -127,-55,-48,40,-29,28,5,55,16,15,13,-11,5, -93,35,-51,-60,17,68,92,46,-12,29,47,51,-18, -116,-25,-79,3,20,-4,48,64,26,7,8,-3,6, 
  /* [2][0][][] */ 92,26,-51,17,-31,-29,26,55,-50,20,10,-22,5, -83,-127,86,43,15,72,31,105,-2,-7,19,21,-66, -113,-89,-13,-9,-23,22,-53,58,69,-33,68,-37,-17, 
  /* [3][0][][] */ -96,-106,59,-94,62,0,45,-14,76,-14,33,-32,2, -7,-86,44,-4,23,48,7,7,58,70,50,40,81, 41,-127,92,-63,12,28,39,-16,82,21,-24,13,-28, 
  /* [4][0][][] */ 101,-45,13,69,-30,-55,-10,36,-89,8,-50,75,41, 41,-44,127,-59,-32,-18,-58,-28,-64,-20,3,-41,-43, -65,22,121,-7,-37,6,-101,-46,-11,13,-22,47,-18, 
  /* [5][0][][] */ -29,1,-4,14,-20,-4,-23,-6,13,1,-18,6,-12, 2,-18,14,4,-9,-3,11,-23,-6,22,-38,2,-15, -7,81,-119,127,-103,23,17,-59,47,-16,-24,19,-12, 
  /* [6][0][][] */ 78,127,-69,28,-34,2,-54,14,-59,-83,-32,1,-20, 29,40,-13,-43,36,48,-33,9,-5,-24,25,-18,30, 84,35,38,-37,10,-33,-22,1,-69,-10,-53,7,11, 
  /* [7][0][][] */ 52,-37,89,41,70,8,-40,35,-26,-53,-6,-14,-34, -127,10,93,15,100,-48,-13,-14,26,-80,-74,61,-35, -11,88,101,38,13,-107,17,60,5,-83,-22,23,-30, 
};
const TfArray<4, int> tensor_dimension15 = { 4, { 8,1,3,13 } };
const TfArray<8, float> quant15_scale = { 8, { 0.0033735709730535746, 0.0038639921694993973, 0.0035920299123972654, 0.0033492965158075094, 0.0037329981569200754, 0.0050543788820505142, 0.0040460987947881222, 0.0033296498004347086, } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&g0::quant14_zero, 0 };
const TfArray<4, int> tensor_dimension16 = { 4, { 1,1,50,13 } };
const TfArray<4, int> tensor_dimension17 = { 4, { 1,1,50,8 } };
const TfArray<1, float> quant17_scale = { 1, { 0.025873484089970589, } };
const TfArray<1, int> quant17_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&quant17_zero, 0 };
const TfArray<4, int> tensor_dimension18 = { 4, { 1,50,1,8 } };
const TfArray<4, int> tensor_dimension19 = { 4, { 1,25,1,8 } };
const TfArray<4, int> tensor_dimension20 = { 4, { 1,1,25,8 } };
const TfArray<4, int> tensor_dimension21 = { 4, { 1,1,25,16 } };
const TfArray<1, float> quant21_scale = { 1, { 0.022955071181058884, } };
const TfLiteAffineQuantization quant21 = { (TfLiteFloatArray*)&quant21_scale, (TfLiteIntArray*)&g0::quant17_zero, 0 };
const TfArray<4, int> tensor_dimension22 = { 4, { 1,25,1,16 } };
const TfArray<4, int> tensor_dimension23 = { 4, { 1,13,1,16 } };
const TfArray<4, int> tensor_dimension24 = { 4, { 1,1,13,16 } };
const TfArray<4, int> tensor_dimension25 = { 4, { 1,1,13,32 } };
const TfArray<1, float> quant25_scale = { 1, { 0.018683955073356628, } };
const TfLiteAffineQuantization quant25 = { (TfLiteFloatArray*)&quant25_scale, (TfLiteIntArray*)&g0::quant17_zero, 0 };
const TfArray<4, int> tensor_dimension26 = { 4, { 1,13,1,32 } };
const TfArray<4, int> tensor_dimension27 = { 4, { 1,7,1,32 } };
const TfArray<2, int> tensor_dimension28 = { 2, { 1,224 } };
const TfArray<2, int> tensor_dimension29 = { 2, { 1,3 } };
const TfArray<1, float> quant29_scale = { 1, { 0.079531364142894745, } };
const TfArray<1, int> quant29_zero = { 1, { -4 } };
const TfLiteAffineQuantization quant29 = { (TfLiteFloatArray*)&quant29_scale, (TfLiteIntArray*)&quant29_zero, 0 };
const TfArray<1, float> quant30_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant30 = { (TfLiteFloatArray*)&quant30_scale, (TfLiteIntArray*)&g0::quant17_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 16 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 16,15,14 } };
const TfArray<1, int> outputs1 = { 1, { 17 } };
const TfLiteReshapeParams opdata2 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs2 = { 2, { 17,2 } };
const TfArray<1, int> outputs2 = { 1, { 18 } };
const TfLitePoolParams opdata3 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs3 = { 1, { 18 } };
const TfArray<1, int> outputs3 = { 1, { 19 } };
const TfLiteReshapeParams opdata4 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs4 = { 2, { 19,3 } };
const TfArray<1, int> outputs4 = { 1, { 20 } };
const TfLiteConvParams opdata5 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 20,13,12 } };
const TfArray<1, int> outputs5 = { 1, { 21 } };
const TfLiteReshapeParams opdata6 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs6 = { 2, { 21,4 } };
const TfArray<1, int> outputs6 = { 1, { 22 } };
const TfLitePoolParams opdata7 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs7 = { 1, { 22 } };
const TfArray<1, int> outputs7 = { 1, { 23 } };
const TfLiteReshapeParams opdata8 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs8 = { 2, { 23,5 } };
const TfArray<1, int> outputs8 = { 1, { 24 } };
const TfLiteConvParams opdata9 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu, 1,1 };
const TfArray<3, int> inputs9 = { 3, { 24,11,10 } };
const TfArray<1, int> outputs9 = { 1, { 25 } };
const TfLiteReshapeParams opdata10 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs10 = { 2, { 25,6 } };
const TfArray<1, int> outputs10 = { 1, { 26 } };
const TfLitePoolParams opdata11 = { kTfLitePaddingSame, 1,2, 1,2, kTfLiteActNone, { { 0,0, 0, 0 } } };
const TfArray<1, int> inputs11 = { 1, { 26 } };
const TfArray<1, int> outputs11 = { 1, { 27 } };
const TfLiteReshapeParams opdata12 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs12 = { 2, { 27,7 } };
const TfArray<1, int> outputs12 = { 1, { 28 } };
const TfLiteFullyConnectedParams opdata13 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs13 = { 3, { 28,9,8 } };
const TfArray<1, int> outputs13 = { 1, { 29 } };
const TfLiteSoftmaxParams opdata14 = { 1 };
const TfArray<1, int> inputs14 = { 1, { 29 } };
const TfArray<1, int> outputs14 = { 1, { 30 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 656), (TfLiteIntArray*)&g0::tensor_dimension0, 650, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 672, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension11, 1536, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data12, (TfLiteIntArray*)&g0::tensor_dimension12, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data13, (TfLiteIntArray*)&g0::tensor_dimension13, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data14, (TfLiteIntArray*)&g0::tensor_dimension14, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data15, (TfLiteIntArray*)&g0::tensor_dimension15, 312, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension16, 650, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 656), (TfLiteIntArray*)&g0::tensor_dimension17, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension18, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension19, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension20, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension21, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 400, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 400), (TfLiteIntArray*)&g0::tensor_dimension23, 208, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension24, 208, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant21))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 416), (TfLiteIntArray*)&g0::tensor_dimension25, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension26, 416, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 416), (TfLiteIntArray*)&g0::tensor_dimension27, 224, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension28, 224, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant25))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 224), (TfLiteIntArray*)&g0::tensor_dimension29, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant29))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension29, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant30))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[15] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs13, (TfLiteIntArray*)&g0::outputs13, (TfLiteIntArray*)&g0::inputs13, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata13)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs14, (TfLiteIntArray*)&g0::outputs14, (TfLiteIntArray*)&g0::inputs14, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata14)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[15] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs13, (TfLiteIntArray*)&g0::outputs13, (TfLiteIntArray*)&g0::inputs13, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata13)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs14, (TfLiteIntArray*)&g0::outputs14, (TfLiteIntArray*)&g0::inputs14, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata14)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_CONV_2D, OP_RESHAPE, OP_MAX_POOL_2D, OP_RESHAPE, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 31, };
const size_t tflNodes_subgraph_index[] = {0, 15, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  30, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

} // end namespace tflite_model_ai
using namespace tflite_model_ai;

TfLiteStatus tflite_learn_922684_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  static EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 31;
  for (size_t i = 0; i < 31; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_MAX_POOL_2D] = Register_MAX_POOL_2D();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_922684_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_922684_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_922684_3_invoke() {
  for (size_t i = 0; i < 15; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_922684_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
